<?php
$schema = new \Doctrine\DBAL\Schema\Schema();
$Block = $schema->createTable("as_blocks");
$Block->addColumn("id", "integer", array("unsigned" => true, "autoincrement" => true));
$Block->setPrimaryKey(array('0'=>'id'));
$Block->addColumn("title", "string", array("length" => 255, 'notnull' => true));
$Block->addColumn("content", "text", array('notnull' => false));
$Block->addColumn("mark", "string", array("length" => 255, 'notnull' => true));
$Block->addUniqueIndex(array('0'=>'mark'));
$Block->addColumn("type", "string", array("length" => 100, 'notnull' => true));
$Block->addColumn("status", "string", array("length" => 100, 'notnull' => true));
$Block->addColumn("sequence", "integer", array("length" => 6, 'notnull' => false));
$Block->addColumn("created", "datetime", array('notnull' => true));
$Block->addColumn("updated", "datetime", array('notnull' => true));
$Configuration = $schema->createTable("as_configurations");
$Configuration->addColumn("id", "integer", array("unsigned" => true, "autoincrement" => true));
$Configuration->setPrimaryKey(array('0'=>'id'));
$Configuration->addColumn("ds_label", "string", array("length" => 255, 'notnull' => true));
$Configuration->addColumn("ds_key", "string", array("length" => 255, 'notnull' => true));
$Configuration->addColumn("ds_value", "string", array("length" => 255, 'notnull' => true));
$Configuration->addColumn("ds_help", "string", array("length" => 255, 'notnull' => true));
$Configuration->addColumn("created", "datetime", array('notnull' => true));
$Configuration->addColumn("updated", "datetime", array('notnull' => true));
$CategoryPages = $schema->createTable("as_categories_pages");
$CategoryPages->addColumn("id", "integer", array("unsigned" => true, "autoincrement" => true));
$CategoryPages->setPrimaryKey(array('0'=>'id'));
$CategoryPages->addColumn("title", "string", array("length" => 255, 'notnull' => true));
$CategoryPages->addColumn("mark", "string", array("length" => 255, 'notnull' => false));
$CategoryPages->addColumn("created", "datetime", array('notnull' => true));
$CategoryPages->addColumn("updated", "datetime", array('notnull' => true));
$CategoryPages->addColumn("slug", "string", array("length" => 255, 'notnull' => true));
$Page = $schema->createTable("as_pages");
$Page->addColumn("id", "integer", array("unsigned" => true, "autoincrement" => true));
$Page->setPrimaryKey(array('0'=>'id'));
$Page->addColumn("title", "string", array("length" => 255, 'notnull' => true));
$Page->addColumn("content", "text", array('notnull' => true));
$Page->addColumn("status", "string", array("length" => 100, 'notnull' => true));
$Page->addColumn("category_id", "integer", array('unsigned' => true, 'notnull' => false));
$Page->addForeignKeyConstraint($CategoryPages, array("category_id"), array("id"));
$Page->addColumn("meta_description", "text", array('notnull' => false));
$Page->addColumn("sequence", "integer", array("length" => 6, 'notnull' => false));
$Page->addColumn("mark", "string", array("length" => 255, 'notnull' => false));
$Page->addColumn("parent_id", "integer", array('unsigned' => true, 'notnull' => false));
$Page->addForeignKeyConstraint($Page, array("parent_id"), array("id"));
$Page->addColumn("created", "datetime", array('notnull' => true));
$Page->addColumn("updated", "datetime", array('notnull' => true));
$Page->addColumn("slug", "string", array("length" => 255, 'notnull' => true));
$CategoryPost = $schema->createTable("as_categories_post");
$CategoryPost->addColumn("id", "integer", array("unsigned" => true, "autoincrement" => true));
$CategoryPost->setPrimaryKey(array('0'=>'id'));
$CategoryPost->addColumn("title", "string", array("length" => 255, 'notnull' => true));
$CategoryPost->addColumn("created", "datetime", array('notnull' => true));
$CategoryPost->addColumn("updated", "datetime", array('notnull' => true));
$CategoryPost->addColumn("slug", "string", array("length" => 255, 'notnull' => true));
$Post = $schema->createTable("as_posts");
$Post->addColumn("id", "integer", array("unsigned" => true, "autoincrement" => true));
$Post->setPrimaryKey(array('0'=>'id'));
$Post->addColumn("title", "string", array("length" => 255, 'notnull' => true));
$Post->addColumn("content", "text", array('notnull' => true));
$Post->addColumn("status", "string", array("length" => 100, 'notnull' => true));
$Post->addColumn("category_id", "integer", array('unsigned' => true, 'notnull' => false));
$Post->addForeignKeyConstraint($CategoryPost, array("category_id"), array("id"));
$Post->addColumn("meta_description", "text", array('notnull' => false));
$Post->addColumn("sequence", "integer", array("length" => 6, 'notnull' => false));
$Post->addColumn("created", "datetime", array('notnull' => true));
$Post->addColumn("updated", "datetime", array('notnull' => true));
$Post->addColumn("slug", "string", array("length" => 255, 'notnull' => true));
$Carousel = $schema->createTable("as_carousels");
$Carousel->addColumn("id", "integer", array("unsigned" => true, "autoincrement" => true));
$Carousel->setPrimaryKey(array('0'=>'id'));
$Carousel->addColumn("title", "string", array("length" => 255, 'notnull' => true));
$Carousel->addColumn("status", "string", array("length" => 100, 'notnull' => true));
$Carousel->addColumn("mark", "string", array("length" => 255, 'notnull' => true));
$Carousel->addColumn("created", "datetime", array('notnull' => true));
$Carousel->addColumn("updated", "datetime", array('notnull' => true));
$Slide = $schema->createTable("as_slides");
$Slide->addColumn("id", "integer", array("unsigned" => true, "autoincrement" => true));
$Slide->setPrimaryKey(array('0'=>'id'));
$Slide->addColumn("title", "string", array("length" => 255, 'notnull' => false));
$Slide->addColumn("image", "string", array("length" => 255, 'notnull' => true));
$Slide->addColumn("description", "text", array('notnull' => false));
$Slide->addColumn("carousel_id", "integer", array('unsigned' => true, 'notnull' => true));
$Slide->addForeignKeyConstraint($Carousel, array("carousel_id"), array("id"));
$Slide->addColumn("sequence", "integer", array("length" => 6, 'notnull' => false));
$Slide->addColumn("created", "datetime", array('notnull' => true));
$Slide->addColumn("updated", "datetime", array('notnull' => true));
$User = $schema->createTable("as_users");
$User->addColumn("id", "integer", array("unsigned" => true, "autoincrement" => true));
$User->setPrimaryKey(array('0'=>'id'));
$User->addColumn("first_name", "string", array("length" => 255, 'notnull' => true));
$User->addColumn("last_name", "string", array("length" => 255, 'notnull' => true));
$User->addColumn("email", "string", array("length" => 100, 'notnull' => true));
$User->addUniqueIndex(array('0'=>'email'));
$User->addColumn("login", "string", array("length" => 100, 'notnull' => true));
$User->addUniqueIndex(array('0'=>'login'));
$User->addColumn("password", "string", array("length" => 255, 'notnull' => true));
$User->addColumn("admin", "string", array("length" => 100, 'notnull' => true));
$User->addColumn("token_email", "string", array("length" => 255, 'notnull' => false));
$User->addColumn("token_email_created", "datetime", array('notnull' => false));
$User->addColumn("token_forgotten", "string", array("length" => 255, 'notnull' => false));
$User->addColumn("token_forgotten_created", "datetime", array('notnull' => false));
$User->addColumn("email_confirm", "string", array("length" => 100, 'notnull' => true));
$User->addColumn("last_logging", "datetime", array('notnull' => false));
$User->addColumn("accept_terms", "string", array("length" => 100, 'notnull' => true));
$User->addColumn("status", "string", array("length" => 100, 'notnull' => true));
$User->addColumn("created", "datetime", array('notnull' => true));
$User->addColumn("updated", "datetime", array('notnull' => true));

return $schema;