CategoryPost:
  options:
    table: categories_posts
    timestampable: true
    translatable: Language
  fields:
    id					: {type: primary, strategy: identity}
    label 				: {type: string, length: 255, notnull: false}
    title				: {type: title, length: 255, notnull: true, translation: true}

Post:
  options:
    table: posts
    timestampable: true
    sluggable: title
    translatable: Language
  fields:
    id					: {type: primary, strategy: identity}
    title				: {type: string, length: 255, notnull: true, translation: true}
    content 		    : {type: editor, translation: true}
    image				: {type: string, length: 255, notnull: false}
    meta_description 	: {type: note, length: 200, notnull: false, translation: true}
    status				: {type: options, values: {0: 'Desactivo', 1: 'Activo', 2: 'Borrador'}, default: 2}
    category:
      type: foreign
      model: CategoryPost
      join: { name: "category_id", foreignField: "id" }
      relation: "many-to-one"
      notnull: false
    sequence 		    : {type: integer, length: 6, notnull: false}