Block:
  options:
    table: blocks
    timestampable: true
    translatable: Language
  fields:
    id					: {type: primary, strategy: identity}
    title				: {type: string, length: 255, notnull: true, translation: true}
    content 		    : {type: editor, translation: true}
    label 				: {type: string, length: 255, unique: true}
    type				: {type: options, values: {'content': 'Contenido'}, default: 'content'}
    status				: {type: options, values: {0: 'Desactivo', 1: 'Activo'}, default: 0}
    sequence 		    : {type: integer, length: 6, notnull: false}