Block:
  options:
    table: blocks
    timestampable: true
  fields:
    id					: {type: primary, strategy: identity}
    label 				: {type: string, length: 255, unique: true}
    type				: {type: options, values: {'content': 'Contenido', 'file': 'Archivo'}, default: 'content'}
    status				: {type: options, values: {0: 'Desactivo', 1: 'Activo'}, default: 0}
    sequence 		    : {type: integer, length: 6, notnull: false}

BlockTranslation:
  options:
    table: blocks_translation
    timestampable: true
    sluggable: [title]
  fields:
    id					: {type: primary, strategy: identity}
    title				: {type: string, length: 255, notnull: true}
    content 		    : {type: editor}
    block:
      type: foreign
      model: Block
      join: { name: "row_parent_id", foreignField: "id" }
      relation: "many-to-one"
    language:
      type: foreign
      model: Language
      join: { name: "language_id", foreignField: "id" }
      relation: "many-to-one"