Configuration:
  options:
    table: configurations
    timestampable: true
  fields:
    id					: {type: primary, strategy: identity}
    title   			: {type: string, length: 255}
    content				: {type: string, length: 255}
    label	    	    : {type: string, length: 255}
    help				: {type: string, length: 255, notnull: true}